services:
  - type: web
    name: my-portfolio-web
    env: node
    branch: main
    root: .
    plan: free
    envVars:
      - key: CORS_ORIGIN
        value: "https://my-portfolio-vgv9.vercel.app"
    buildCommand: "npm run build"
    startCommand: "npm start"
